- name: nginx install and run
  hosts: all
  become: yes
  serial: 2
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogenous modeuls that can work for all distributions
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service: #heterogenous modeuls that can work for all distributions
      name: nginx
      state: started
      enabled: yes